package com.spshop.model.query;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.spshop.model.Component;


public class QueryResult <T extends Component> implements Cloneable, Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 5054010552469364355L;
	
	private String componentType;
	
	private int recordCount = 0;
	
	private List<T> result= new ArrayList<T>();
	
	
	public QueryResult() {
	}
	
	public void setRecordCount(int recordCount) {
		this.recordCount = recordCount;
	}

	public int getRecordCount() {
		return recordCount;
	}

	public void setComponentType(String componentType) {
		this.componentType = componentType;
	}

	public String getComponentType() {
		return componentType;
	}

	public void setResult(List<T> result) {
		this.result = result;
	}

	public List<T> getResult() {
		return result;
	}
	
	@SuppressWarnings("unchecked")
	public <Y extends Component> List<Y> toSpecificResult(){
		List<Y> rs = new ArrayList<Y>();
		for(Component c : getResult()){
			rs.add((Y)c);
		}
		return rs;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	@SuppressWarnings("unchecked")
	public QueryResult<T> clone() {
		QueryResult<T> obj = null;
		obj = new QueryResult<T>();
		if (this.componentType != null) {
			/* Does not have a clone() method */
			obj.componentType = this.componentType;
		}
		obj.recordCount = this.recordCount;
		if (this.result != null) {
			obj.result = new ArrayList<T>();
			for (Component it : this.result) {
				obj.result.add((T)it.clone());
			}
		}
		return obj;
	}
	
}
