package com.spshop.model;

public class Address extends Component{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String firstName;
	
	private String lastName;

	private String address1;

	private String address2;

	private String city;

	private String stateProvince;

	private String country;

	private String postalCode;

	private String phone;

	
	public Address() {
	}
	public Address(Address address) {
	    super(address);
    }
	public Address(String firstName, String LastName, String address1, String address2,
			String city, String stateProvince, String country, String postalCode,
			String phone) {
		this.setFirstName(firstName);
		this.setLastName(LastName);
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.stateProvince = stateProvince;
		this.country = country;
		this.postalCode = postalCode;
		this.phone = phone;
	}


	public String getAddress1() {
		return address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getStateProvince() {
		return stateProvince;
	}

	public void setStateProvince(String stateProvince) {
		this.stateProvince = stateProvince;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getPostalCode() {
		return postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public Address clone() {
		Address obj = null;
		obj = new Address(this);
		if (this.firstName != null) {
			/* Does not have a clone() method */
			obj.firstName = this.firstName;
		}
		if (this.lastName != null) {
			/* Does not have a clone() method */
			obj.lastName = this.lastName;
		}
		if (this.address1 != null) {
			/* Does not have a clone() method */
			obj.address1 = this.address1;
		}
		if (this.address2 != null) {
			/* Does not have a clone() method */
			obj.address2 = this.address2;
		}
		if (this.city != null) {
			/* Does not have a clone() method */
			obj.city = this.city;
		}
		if (this.stateProvince != null) {
			/* Does not have a clone() method */
			obj.stateProvince = this.stateProvince;
		}
		obj.country = this.country;
		if (this.postalCode != null) {
			/* Does not have a clone() method */
			obj.postalCode = this.postalCode;
		}
		if (this.phone != null) {
			/* Does not have a clone() method */
			obj.phone = this.phone;
		}
		return obj;
	}
}
