package com.spshop.model;

public class AddressBook extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = 4153841943340205663L;
	
	private String address;
	
	public AddressBook() {
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public AddressBook clone() {
		AddressBook obj = null;
		obj = new AddressBook();
		if (this.address != null) {
			/* Does not have a clone() method */
			obj.address = this.address;
		}
		return obj;
	}
	
}
