package com.spshop.model;

import java.util.List;

public class Comment extends Component{
	
	public Comment() {
		// TODO Auto-generated constructor stub
	}
	/**
	 * 
	 */
	private static final long serialVersionUID = 4838385664945447761L;
	
	private List<Comment> replyList;
	private String content;
	private int rate;
	private User user;
	private Product product;
	
	public List<Comment> getReplyList() {
		return replyList;
	}
	public void setReplyList(List<Comment> replyList) {
		this.replyList = replyList;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public int getRate() {
		return rate;
	}
	public void setRate(int rate) {
		this.rate = rate;
	}
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}
	public Product getProduct() {
		return product;
	}
	public void setProduct(Product product) {
		this.product = product;
	}
	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public Comment clone() {
		Comment obj = null;
		obj = new Comment();
		if (this.replyList != null) {
			/* Does not have a clone() method */
			obj.replyList = this.replyList;
		}
		if (this.content != null) {
			/* Does not have a clone() method */
			obj.content = this.content;
		}
		obj.rate = this.rate;
		if (this.user != null) {
			obj.user = (User) this.user.clone();
		}
		if (this.product != null) {
			obj.product = (Product) this.product.clone();
		}
		return obj;
	}
}
