package com.spshop.model;

import com.spshop.model.enums.ValueType;

public class Configuration extends Component{
	/**
	 * 
	 */
	private static final long serialVersionUID = -6830864436623220292L;
	private String value;
	private String strType;
	
	public Configuration() {
		// TODO Auto-generated constructor stub
	}
	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}
	public ValueType getType() {
		if(null==strType){
			return null;
		}
		return ValueType.valueOf(strType.toUpperCase());
	}
	public void setType(ValueType type) {
		this.strType = type.getValue();
	}
	public void setStrType(String strType) {
		this.strType = strType;
	}
	public String getStrType() {
		return strType;
	}
	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public Configuration clone() {
		Configuration obj = null;
		obj = new Configuration();
		if (this.value != null) {
			/* Does not have a clone() method */
			obj.value = this.value;
		}
		if (this.strType != null) {
			/* Does not have a clone() method */
			obj.strType = this.strType;
		}
		return obj;
	}
}
