package com.spshop.model;

public class Country extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = 168229983824448541L;
	
	private String code;
	private String abbrCode;
	private float dePrice;
	private float adDePrice;
	private float freeDePrice;
	private float freeAdDePrice;
	
	public Country() {
	}
	
	public Country(Country country) {
		super(country);
	}
	
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getAbbrCode() {
		return abbrCode;
	}
	public void setAbbrCode(String abbrCode) {
		this.abbrCode = abbrCode;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public Country clone() {
		Country obj = null;
		obj = new Country(this);
		if (this.code != null) {
			/* Does not have a clone() method */
			obj.code = this.code;
		}
		if (this.abbrCode != null) {
			/* Does not have a clone() method */
			obj.abbrCode = this.abbrCode;
		}
		obj.dePrice = this.dePrice;
		obj.adDePrice = this.adDePrice;
		obj.freeDePrice = this.freeDePrice;
		obj.freeAdDePrice = this.freeAdDePrice;
		
		return obj;
	}

	public void setDePrice(float dePrice) {
		this.dePrice = dePrice;
	}

	public float getDePrice() {
		return dePrice;
	}

	public void setAdDePrice(float adDePrice) {
		this.adDePrice = adDePrice;
	}

	public float getAdDePrice() {
		return adDePrice;
	}

	public float getFreeDePrice() {
		return freeDePrice;
	}

	public void setFreeDePrice(float freeDePrice) {
		this.freeDePrice = freeDePrice;
	}

	public float getFreeAdDePrice() {
		return freeAdDePrice;
	}

	public void setFreeAdDePrice(float freeAdDePrice) {
		this.freeAdDePrice = freeAdDePrice;
	}
	
	
}
