package com.spshop.model;

public class CutOff extends Promotion{

	/**
	 * 
	 */
	private static final long serialVersionUID = -562444859345858925L;
	
	private int percent;

	public CutOff() {
		// TODO Auto-generated constructor stub
	}
	
	public void setPercent(int percent) {
		this.percent = percent;
	}

	public int getPercent() {
		return percent;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public CutOff clone() {
		CutOff obj = null;
		obj = new CutOff();
		obj.percent = this.percent;
		return obj;
	}

}
