package com.spshop.model;

public class Deliver extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = -817593465733096672L;
	
	private String company;
	private float price;
	
	private Country country;
	
	public Deliver() {
	}
	
	public Deliver(Deliver deliver) {
		super(deliver);
	}
	
	public String getCompany() {
		return company;
	}
	public void setCompany(String company) {
		this.company = company;
	}
	public float getPrice() {
		return price;
	}
	public void setPrice(float price) {
		this.price = price;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public Country getCountry() {
		return country;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public Deliver clone() {
		Deliver obj = null;
		obj = new Deliver(this);
		if (this.company != null) {
			obj.company = this.company;
		}
		obj.price = this.price;
		if (this.country != null) {
			obj.country = (Country) this.country.clone();
		}
		return obj;
	}
	
	
}
