package com.spshop.model;

public class Message extends Component {
    /**
     *
     */
    private static final long serialVersionUID = -5880597742035898505L;
    
    private String content;

    private Message replyTo;
    private Message replyBy;
    private User user;
    private boolean replied;

    public Message(){
        
    }
    
    public Message(Message msg){
        super(msg);
    }
    
    public User getUser() {
        return user;
    }
    
    public Message getReplyTo() {
        return replyTo;
    }
    
    public void setReplyTo(Message replyTo) {
        this.replyTo = replyTo;
    }
    public void setUser(User user) {
        this.user = user;
    }
    
    public String getContent() {
        return content;
    }
    public void setContent(String content) {
        this.content = content;
    }
    public void setReplied(boolean isReplied) {
        this.replied = isReplied;
    }

    public boolean isReplied() {
        return replied;
    }

    /**
     * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
     * clone
     * @return Object
     */
    public Message clone(boolean includeParent) {
        Message obj = null;
        obj = new Message(this);
        if (this.content != null) {
            /* Does not have a clone() method */
            obj.content = this.content;
        }
        if (this.user != null) {
            obj.user = (User) this.user.clone();
        }
        if (this.replyBy != null) {
            /* Does not have a clone() method */
            obj.replyBy = new Message();
            if(null!=this.replyBy){
                Message m = this.replyBy.clone(false);
                m.setReplyTo(obj);
                obj.replyBy = m;
            }
        }
        if (this.replyTo != null) {
            if (includeParent&&this.replyTo != null) {
                obj.replyTo = (Message) this.replyTo.clone();
            }
        }
        obj.replied = this.replied;
        return obj;
    }
    
    public Message clone() {
        return this.clone(true);
    }

    public void setReplyBy(Message replyBy) {
        this.replyBy = replyBy;
    }

    public Message getReplyBy() {
        return replyBy;
    }


    


    
}
