package com.spshop.model;

public class Newsletter extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = -2080852687949263927L;
	private String email;
	public Newsletter() {
		// TODO Auto-generated constructor stub
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getEmail() {
		return email;
	}
	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public Newsletter clone() {
		Newsletter obj = null;
		obj = new Newsletter();
		if (this.email != null) {
			/* Does not have a clone() method */
			obj.email = this.email;
		}
		return obj;
	}

}
