package com.spshop.model;

public class ProductOptionItem extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = -3876490399646625342L;
	private String value;
	private Image icon;
	private String altTitle;
	private String displayName;
	private ProductOption option;
	private float priceChange;
	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}
	public Image getIcon() {
		return icon;
	}
	public void setIcon(Image icon) {
		this.icon = icon;
	}
	public String getAltTitle() {
		return altTitle;
	}
	public void setAltTitle(String altTitle) {
		this.altTitle = altTitle;
	}
	public String getDisplayName() {
		return displayName;
	}
	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}
	public void setOption(ProductOption option) {
		this.option = option;
	}
	public ProductOption getOption() {
		return option;
	}
	public ProductOptionItem() {
		// TODO Auto-generated constructor stub
	}
	public ProductOptionItem(ProductOptionItem productOptionItem) {
		super(productOptionItem);
	}
	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public ProductOptionItem clone() {
		return clone(true);
	}
	public ProductOptionItem clone(boolean withOption) {
		ProductOptionItem obj = null;
		obj = new ProductOptionItem(this);
		
		obj.priceChange = this.priceChange;
		
		if (this.value != null) {
			/* Does not have a clone() method */
			obj.value = this.value;
		}
		if (this.icon != null) {
			obj.icon = (Image) this.icon.clone();
		}
		if (this.altTitle != null) {
			/* Does not have a clone() method */
			obj.altTitle = this.altTitle;
		}
		if (this.displayName != null) {
			/* Does not have a clone() method */
			obj.displayName = this.displayName;
		}
		if(withOption){
			if (this.option != null) {
				obj.option = (ProductOption) this.option.clone();
			}
		}
		return obj;
	}
	public float getPriceChange() {
		return priceChange;
	}
	public void setPriceChange(float priceChange) {
		this.priceChange = priceChange;
	}
	
}
