package com.spshop.model;

public class ProductProperty extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = -2299775829083584745L;
	private String name;
	private String value;
	private Product product;
	
	
	
	public ProductProperty(ProductProperty productProperty) {
		super(productProperty);
	}
	
	public ProductProperty() {
	}



	public String getName() {
		return name;
	}



	public void setName(String name) {
		this.name = name;
	}



	public String getValue() {
		return value;
	}



	public void setValue(String value) {
		this.value = value;
	}



	public Product getProduct() {
		return product;
	}



	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * @param withProduct 
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public ProductProperty clone(boolean withProduct) {
		ProductProperty obj = null;
		obj = new ProductProperty(this);
		if (this.name != null) {
			/* Does not have a clone() method */
			obj.name = this.name;
		}
		if (this.value != null) {
			/* Does not have a clone() method */
			obj.value = this.value;
		}
		if(withProduct){
			if (this.product != null) {
				obj.product = (Product) this.product.clone();
			}
		}
		return obj;
	}
	
	public ProductProperty clone(){
		return clone(true);
	}

}