package com.spshop.model;

import java.util.Date;

import com.spshop.model.enums.PromotionStatusType;

public class Promotion extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1639192819712035933L;
	
	private Date startDate;
	private Date endDate;
	
	private String strStatus;
	
	public Promotion() {
		// TODO Auto-generated constructor stub
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public PromotionStatusType getStatus() {
		if(null==strStatus){
			return null;
		}
		return PromotionStatusType.valueOf(strStatus.toUpperCase());
	}

	public void setStatus(PromotionStatusType status) {
		this.strStatus = status.getValue();
	}

	public void setStrStatus(String strStatus) {
		this.strStatus = strStatus;
	}

	public String getStrStatus() {
		return strStatus;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public Promotion clone() {
		Promotion obj = null;
		obj = new Promotion();
		if (this.startDate != null) {
			obj.startDate = (Date) this.startDate.clone();
		}
		if (this.endDate != null) {
			obj.endDate = (Date) this.endDate.clone();
		}
		if (this.strStatus != null) {
			/* Does not have a clone() method */
			obj.strStatus = this.strStatus;
		}
		return obj;
	}


}
