package com.spshop.model;

public class SearchHistory extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = -171181992951022870L;
	
	private String keywords;
	private String hit;
	
	public SearchHistory() {
		// TODO Auto-generated constructor stub
	}
	
	public String getKeywords() {
		return keywords;
	}
	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}
	public String getHit() {
		return hit;
	}
	public void setHit(String hit) {
		this.hit = hit;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public SearchHistory clone() {
		SearchHistory obj = null;
		obj = new SearchHistory();
		if (this.keywords != null) {
			/* Does not have a clone() method */
			obj.keywords = this.keywords;
		}
		if (this.hit != null) {
			/* Does not have a clone() method */
			obj.hit = this.hit;
		}
		return obj;
	}

}
