package com.spshop.model;

public class ShopBasket extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = 3326758863003867522L;
	
	private User user;
	private ShopBasketItem items;
	
	public ShopBasket() {
		// TODO Auto-generated constructor stub
	}
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}
	public ShopBasketItem getItems() {
		return items;
	}
	public void setItems(ShopBasketItem items) {
		this.items = items;
	}
	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public ShopBasket clone() {
		ShopBasket obj = null;
		obj = new ShopBasket();
		if (this.user != null) {
			obj.user = (User) this.user.clone();
		}
		if (this.items != null) {
			obj.items = (ShopBasketItem) this.items.clone();
		}
		return obj;
	}
	
}
