package com.spshop.model;

import com.spshop.model.enums.SelectType;

public class UserOption extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1976590524674580292L;
	
	private String optionName;
	private String value;
	private float priceChange;
	private String strOptionType;
	//private OrderItem orderItem;
	
	public UserOption() {
		// TODO Auto-generated constructor stub
	}
	
	public UserOption(UserOption option) {
		super(option);
	}
	
	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}

	public String getOptionName() {
		return optionName;
	}

	public void setOptionName(String optionName) {
		this.optionName = optionName;
		setName(optionName);
	}

	public String getStrOptionType() {
		return strOptionType;
	}

	public void setStrOptionType(String strOptionType) {
		this.strOptionType = strOptionType;
	}

	public void setOptionType(SelectType selectType) {
		this.strOptionType = selectType.getValue();
	}
	
	public SelectType getOptionType() {
		return SelectType.valueOf(strOptionType);
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public UserOption clone() {
		UserOption obj = null;
		obj = new UserOption(this);
		obj.priceChange = this.priceChange;
		if (this.optionName != null) {
			/* Does not have a clone() method */
			obj.optionName = this.optionName;
		}
		if (this.value != null) {
			/* Does not have a clone() method */
			obj.value = this.value;
		}
		if (this.strOptionType != null) {
			/* Does not have a clone() method */
			obj.strOptionType = this.strOptionType;
		}
		return obj;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (getClass() != obj.getClass())
			return false;
		UserOption other = (UserOption) obj;
		if (optionName == null) {
			if (other.optionName != null)
				return false;
		} else if (!optionName.equals(other.optionName))
			return false;
		if (strOptionType == null) {
			if (other.strOptionType != null)
				return false;
		} else if (!strOptionType.equals(other.strOptionType))
			return false;
		if (value == null) {
			if (other.value != null)
				return false;
		} else if (!value.equals(other.value))
			return false;
		return true;
	}

	public float getPriceChange() {
		return priceChange;
	}

	public void setPriceChange(float priceChange) {
		this.priceChange = priceChange;
	}
	
	
	
	
}
