package com.spshop.model;

/**
 * Change to use cookie
 * @author Spark.Zhu
 *
 */
@Deprecated
public class VistorHistory extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1106164017074415413L;

	public VistorHistory() {
		// TODO Auto-generated constructor stub
	}
	//private User user;
	//private List<Product> list;

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public VistorHistory clone() {
		VistorHistory obj = null;
		obj = new VistorHistory();
		return obj;
	}

}
